name: dinov2_vits14
architecture: dinov2
pretrained: true
trainable_transformer_blocks: [11]

backbone:
  model_name: dinov2_vits14
  hidden_dim: 384
  resize_size: 224
  crop_size: 224
  normalize: true

head:
  hidden_dims: [128]
  dropout: 0.4
  
output:
  num_bins: 43 
  bin_width: 2.0
  angle_range: [0, 90]

augmentation:
  horizontal_flip: 0.5
  resized_crop_scale: [0.8, 1.0]
  brightness: 0.3
  contrast: 0.3 
  saturation: 0
  gaussian_noise: 0.02
  grayscale_prob: 0.5
  distance_dimming_prob: 0.1
  d0: 1.0
  min_intensity: 0.1