# Input settings - can be overridden via command line
pretrained_model_path: data/checkpoint/AngleCamV2.pth # Path to the pretrained model
image_path: examples/images # Path to the image(s) to be processed
output_dir: data/inference # Path to the output directory

# Inference settings
# Number of images to process in parallel - should be adjusted based on the available memory of the GPU
batch_size: 8 

# Number of workers to use for loading the images - should be adjusted based on the available CPU cores
num_workers: 8 