defaults:
  - _self_
  - model: ../model/model.yaml
  - training: ../core/training.yaml
  - inference: ../core/inference.yaml
  - fit_dist: ../utils/fit_beta_distribution.yaml

# Global settings
device: auto  # auto, cpu, cuda:1, mps
seed: 1234 #42 #1234

# Data paths
data:
  train_csv: data/01_Training_Validation_Data/splits/training.csv
  val_csv: data/01_Training_Validation_Data/splits/validation.csv
  data_dir: data/01_Training_Validation_Data/image_data