defaults:
  - _self_
  - model: ../model/model.yaml
  - training: ../core/training.yaml
  - inference: ../core/inference.yaml
  - fit_dist: ../utils/fit_beta_distribution.yaml

# Global settings
device: cuda:0  # auto, cpu, cuda:1, mps
seed: 1234 #42 #1234

# Data paths
data:
  train_csv: data/model/input/training.csv
  val_csv: data/model/input/validation.csv
  data_dir: data/images/training_validation